# Generated by Django 4.0.2 on 2022-02-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
