# Generated by Django 4.0.2 on 2022-03-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='email',
            new_name='email_id',
        ),
    ]
