# Generated by Django 4.0.2 on 2022-03-01 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_email_login_email_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='email_id',
            new_name='email',
        ),
    ]
